### ISSUE TITLE
добавить категорию

### ISSUE THREAD

**Issue by melezhik** [Spigell/zabbix-hosts#1]
Приветствую! Огромное спасибо за вклад в проект Sparrow. Вы - первый автор после меня sparrow плагинов!

В sparrow есть незадокументированная фича - категории , вы можете задать категорию для плагина, для того что бы упросить его поиск через SparrowHub, для этого в sparrowfile добавляете:

```
"category" : "category name"
```

Вот список разрешенных категорий ( при использование категории вне списка - будет выдана ошибка, так же очевидно можно вообще не указывать категорию )

```
applications
utilities
monitoring
build tools
test tools
applications tests
services tests
chef cookbooks tests
cpan modules tests
os tests
sparrowdo
misc
selftest
examples
```

**Comment by Spigell** [comment]
Спасибо. Да, я заметил это поле. Добавил в некоторые свои плагины. Попробовал через запятую несколько указать - получил 400 ошибку.
